--- #YAML:1.0
name:                Convert-zBase32
version:             0.0100
abstract:            Convert human-oriented base-32 encoded strings
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philip Gwyn <fil@localdomain>
